# Generated by Django 4.2.5 on 2023-12-13 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0012_order_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='time',
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('Delivery', 'Delivery'), ('SelfPickUp', 'Self Pick Up'), ('Pending', 'Pending Assignment')], default='Pending', max_length=20),
        ),
    ]
