# Generated by Django 4.2.5 on 2023-12-14 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0015_alter_order_delivery_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_status',
        ),
        migrations.AddField(
            model_name='deliverycrew',
            name='delivery_status',
            field=models.CharField(choices=[('Delivery', 'Delivery'), ('SelfPickUp', 'Self Pick Up'), ('Pending', 'Pending Assignment')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Pending Assignment'), ('Assigned', 'Assigned'), ('Delivered', 'Delivered')], default='Pending', max_length=20),
        ),
    ]
