# Generated by Django 4.2.5 on 2023-12-17 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0017_deliverycrew_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deliverystatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_status', models.CharField(choices=[('Delivery', 'Delivery'), ('SelfPickUp', 'Self Pick Up'), ('Pending', 'Pending Assignment')], max_length=20)),
                ('is_available', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_crew',
        ),
        migrations.DeleteModel(
            name='DeliveryCrew',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.deliverystatus'),
        ),
    ]
